spring.application.name=hospitalProject
# C?U HÌNH SERVER

server.port=8080

# C?U HÌNH K?T N?I DATABASE

spring.datasource.url=jdbc:mysql://localhost:3306/HospitalManagement

# Tên ??ng nh?p (m?c ??nh là root)
spring.datasource.username=root

# M?t kh?u (nh?p ?úng m?t kh?u ?ã ??t khi cài MySQL)
spring.datasource.password=1234

# Driver class (MySQL 8 dùng driver này)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
